[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string[]]$Tags,

    [string]$RepositoryPath = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,

    [string]$OutputPath = 'FULL_CHANGELOG.md'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repository = (Resolve-Path -LiteralPath $RepositoryPath).Path
$tagResolver = Join-Path $PSScriptRoot 'resolve-release-tag.ps1'

function Invoke-Git {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [int[]]$AllowedExitCodes = @(0)
    )

    $lines = @(& git -C $repository @Arguments 2>&1 | ForEach-Object { [string]$_ })
    $exitCode = $LASTEXITCODE
    if ($AllowedExitCodes -notcontains $exitCode) {
        $details = ($lines -join "`n").Trim()
        if ($details) {
            throw "git $($Arguments -join ' ') failed with exit code ${exitCode}: $details"
        }
        throw "git $($Arguments -join ' ') failed with exit code $exitCode."
    }

    [pscustomobject]@{
        ExitCode = $exitCode
        Lines = $lines
        Text = $lines -join "`n"
    }
}

function Get-TagRecord {
    param([Parameter(Mandatory = $true)][string]$Tag)

    try {
        $release = & $tagResolver -Tag $Tag | ConvertFrom-Json
    } catch {
        throw "Released tag '$Tag' is invalid: $($_.Exception.Message)"
    }

    $commitResult = Invoke-Git -Arguments @('rev-parse', '--verify', "refs/tags/$Tag^{commit}")
    $commit = $commitResult.Text.Trim()
    if (-not $commit) {
        throw "Released tag '$Tag' did not resolve to a commit."
    }

    $createdResult = Invoke-Git -Arguments @(
        'for-each-ref',
        '--format=%(creatordate:unix)',
        "refs/tags/$Tag"
    )
    $createdText = $createdResult.Text.Trim()
    if (-not $createdText) {
        throw "Released tag '$Tag' does not exist."
    }

    $productName = switch ($release.product) {
        'note' { 'BetterHvNote' }
        'notelink' { 'NoteLink' }
        default { throw "Unsupported release product '$($release.product)'." }
    }

    [pscustomobject]@{
        Tag = $Tag
        Product = [string]$release.product
        ProductName = $productName
        Version = [string]$release.version
        SemanticVersion = [version]$release.version
        Commit = $commit
        CreatedAt = [long]::Parse(
            $createdText,
            [Globalization.CultureInfo]::InvariantCulture
        )
        PreviousCommit = $null
    }
}

function Test-GeneratedCommit {
    param([Parameter(Mandatory = $true)][string]$Commit)

    $trailers = Invoke-Git -Arguments @(
        'show',
        '--no-patch',
        '--format=%(trailers:key=Changelog-Generated,valueonly)',
        $Commit
    )
    @($trailers.Lines | Where-Object { $_.Trim() -ieq 'true' }).Count -gt 0
}

function Get-CommitMessageLines {
    param([Parameter(Mandatory = $true)][string]$Commit)

    $message = Invoke-Git -Arguments @('show', '--no-patch', '--format=%B', $Commit)
    $lines = [Collections.Generic.List[string]]::new()
    foreach ($line in $message.Lines) {
        if ($line -match '(?i)^Signed-off-by:\s*') {
            continue
        }
        $lines.Add($line)
    }
    while ($lines.Count -gt 0 -and $lines[$lines.Count - 1] -eq '') {
        $lines.RemoveAt($lines.Count - 1)
    }
    $lines
}

if ($Tags.Count -eq 0) {
    throw 'At least one released tag is required.'
}

$seenTags = @{}
$records = [Collections.Generic.List[object]]::new()
foreach ($tag in $Tags) {
    if ($seenTags.ContainsKey($tag)) {
        throw "Released tag '$tag' was supplied more than once."
    }
    $seenTags[$tag] = $true
    $records.Add((Get-TagRecord -Tag $tag))
}

foreach ($product in @('note', 'notelink')) {
    $productRecords = @(
        $records |
            Where-Object Product -eq $product |
            Sort-Object SemanticVersion
    )
    for ($index = 1; $index -lt $productRecords.Count; $index++) {
        $previous = $productRecords[$index - 1]
        $current = $productRecords[$index]
        $ancestry = Invoke-Git -Arguments @(
            'merge-base',
            '--is-ancestor',
            $previous.Commit,
            $current.Commit
        ) -AllowedExitCodes @(0, 1)
        if ($ancestry.ExitCode -ne 0) {
            throw "Release history for '$product' is non-linear: tag '$($previous.Tag)' is not an ancestor of '$($current.Tag)'."
        }
        $current.PreviousCommit = $previous.Commit
    }
}

$orderedRecords = @(
    $records | Sort-Object -Property @(
        @{ Expression = 'CreatedAt'; Descending = $true },
        @{ Expression = 'Tag'; Descending = $true }
    )
)

$content = [Text.StringBuilder]::new()
[void]$content.Append("<!-- Generated by .github/scripts/generate-full-changelog.ps1. Do not edit manually. -->`n`n")

foreach ($record in $orderedRecords) {
    [void]$content.Append("# $($record.ProductName) $($record.Version)`n`n")

    $revision = if ($record.PreviousCommit) {
        "$($record.PreviousCommit)..$($record.Commit)"
    } else {
        $record.Commit
    }
    $commits = (Invoke-Git -Arguments @('rev-list', '--topo-order', $revision)).Lines

    foreach ($commit in $commits) {
        if (-not $commit -or (Test-GeneratedCommit -Commit $commit)) {
            continue
        }

        $shortHash = (Invoke-Git -Arguments @('rev-parse', '--short=7', $commit)).Text.Trim()
        $messageLines = @(Get-CommitMessageLines -Commit $commit)
        if ($messageLines.Count -eq 0) {
            throw "Commit '$commit' has an empty message."
        }

        [void]$content.Append("[$shortHash] $($messageLines[0])`n")
        for ($lineIndex = 1; $lineIndex -lt $messageLines.Count; $lineIndex++) {
            $line = $messageLines[$lineIndex]
            [void]$content.Append("    $line`n")
        }
        [void]$content.Append("`n")
    }
}

$resolvedOutput = if ([IO.Path]::IsPathRooted($OutputPath)) {
    [IO.Path]::GetFullPath($OutputPath)
} else {
    [IO.Path]::GetFullPath((Join-Path $repository $OutputPath))
}
$outputDirectory = [IO.Path]::GetDirectoryName($resolvedOutput)
if ($outputDirectory) {
    [IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
}
[IO.File]::WriteAllText(
    $resolvedOutput,
    $content.ToString(),
    [Text.UTF8Encoding]::new($false)
)

Write-Output $resolvedOutput
